version: 1.0.{build}

os: Windows Server 2012 R2

environment:
  HOST: localhost
  SQLUSER: sa
  SQLPASSWORD: Password12!
  DATABASE: test
  matrix:
    - PYTHON: "C:\\Python36"
      DJANGOVER: 1.11.3
      SQLINSTANCE: SQL2016
    - PYTHON: "C:\\Python27"
      DJANGOVER: 1.11.3
      SQLINSTANCE: SQL2016
    - PYTHON: "C:\\Python36"
      DJANGOVER: 1.10.7
      SQLINSTANCE: SQL2016
    - PYTHON: "C:\\Python36"
      DJANGOVER: 1.9.13
      SQLINSTANCE: SQL2016
    - PYTHON: "C:\\Python36"
      DJANGOVER: 1.11.3
      SQLINSTANCE: SQL2014
    - PYTHON: "C:\\Python36"
      DJANGOVER: 1.11.3
      SQLINSTANCE: SQL2012SP1

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - python --version
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""
  - pip install django==%DJANGOVER%
  - pip install enum34
  - pip install python-memcached <= 1.53
  - pip install mock codecov
  - pip install -e .

build_script:
  - python setup.py sdist

before_test:
  # setup SQL Server
  - ps: |
      $instanceName = $env:SQLINSTANCE
      Start-Service "MSSQL`$$instanceName"
      Start-Service "SQLBrowser"
  - sqlcmd -S "(local)\%SQLINSTANCE%" -Q "Use [master]; CREATE DATABASE test;"
  - sqlcmd -S "(local)\%SQLINSTANCE%" -h -1 -Q "set nocount on; Select @@version"


test_script:
  - coverage run tests/runtests.py --noinput --settings=test_mssql --debug-sql
  - codecov
